//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ComService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://receptionplatform.java.com/", ConfigurationName="ComService.ComEndpoint")]
    public interface ComEndpoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément fileName de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://receptionplatform.java.com/ComEndpoint/checkFileOperationRequest", ReplyAction="http://receptionplatform.java.com/ComEndpoint/checkFileOperationResponse")]
        ClientApplication.ComService.checkFileOperationResponse checkFileOperation(ClientApplication.ComService.checkFileOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://receptionplatform.java.com/ComEndpoint/checkFileOperationRequest", ReplyAction="http://receptionplatform.java.com/ComEndpoint/checkFileOperationResponse")]
        System.Threading.Tasks.Task<ClientApplication.ComService.checkFileOperationResponse> checkFileOperationAsync(ClientApplication.ComService.checkFileOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkFileOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkFileOperation", Namespace="http://receptionplatform.java.com/", Order=0)]
        public ClientApplication.ComService.checkFileOperationRequestBody Body;
        
        public checkFileOperationRequest() {
        }
        
        public checkFileOperationRequest(ClientApplication.ComService.checkFileOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkFileOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cypherKey;
        
        public checkFileOperationRequestBody() {
        }
        
        public checkFileOperationRequestBody(string fileName, string fileContent, string cypherKey) {
            this.fileName = fileName;
            this.fileContent = fileContent;
            this.cypherKey = cypherKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkFileOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkFileOperationResponse", Namespace="http://receptionplatform.java.com/", Order=0)]
        public ClientApplication.ComService.checkFileOperationResponseBody Body;
        
        public checkFileOperationResponse() {
        }
        
        public checkFileOperationResponse(ClientApplication.ComService.checkFileOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkFileOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string operationResult;
        
        public checkFileOperationResponseBody() {
        }
        
        public checkFileOperationResponseBody(string operationResult) {
            this.operationResult = operationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComEndpointChannel : ClientApplication.ComService.ComEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComEndpointClient : System.ServiceModel.ClientBase<ClientApplication.ComService.ComEndpoint>, ClientApplication.ComService.ComEndpoint {
        
        public ComEndpointClient() {
        }
        
        public ComEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.ComService.checkFileOperationResponse ClientApplication.ComService.ComEndpoint.checkFileOperation(ClientApplication.ComService.checkFileOperationRequest request) {
            return base.Channel.checkFileOperation(request);
        }
        
        public string checkFileOperation(string fileName, string fileContent, string cypherKey) {
            ClientApplication.ComService.checkFileOperationRequest inValue = new ClientApplication.ComService.checkFileOperationRequest();
            inValue.Body = new ClientApplication.ComService.checkFileOperationRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.fileContent = fileContent;
            inValue.Body.cypherKey = cypherKey;
            ClientApplication.ComService.checkFileOperationResponse retVal = ((ClientApplication.ComService.ComEndpoint)(this)).checkFileOperation(inValue);
            return retVal.Body.operationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.ComService.checkFileOperationResponse> ClientApplication.ComService.ComEndpoint.checkFileOperationAsync(ClientApplication.ComService.checkFileOperationRequest request) {
            return base.Channel.checkFileOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.ComService.checkFileOperationResponse> checkFileOperationAsync(string fileName, string fileContent, string cypherKey) {
            ClientApplication.ComService.checkFileOperationRequest inValue = new ClientApplication.ComService.checkFileOperationRequest();
            inValue.Body = new ClientApplication.ComService.checkFileOperationRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.fileContent = fileContent;
            inValue.Body.cypherKey = cypherKey;
            return ((ClientApplication.ComService.ComEndpoint)(this)).checkFileOperationAsync(inValue);
        }
    }
}
